version: 2

jobs:
  test:
    docker:
    - image: carapaceio/go:1.11
    environment:
      - GO111MODULE: "on"

    steps:
    - checkout

    - restore_cache:
        keys:
        - v1-pkg-cache

    - save_cache:
        key: v1-pkg-cache
        paths:
        - "/go/pkg"

    - run:
        name: Get dependencies
        command: |
          go build ./...

    - run:
        name: Test and run linters.
        command: |
          go test -v -race
#          golangci-lint run # golangci lint does not yet support go modules :(


workflows:
  version: 2
  tests:
    jobs: [test]